# Getting start with pandas

## Introduction to pandas Data Structures

In [1]:
import pandas as pd 
import numpy as np

In [2]:
from pandas import Series, DataFrame

### Series

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

np.int64(-5)

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
 sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = pd.Series(sdata, index=states)

In [23]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

### DataFrame

In [34]:
data = {'state':['ohio','ohio','ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [35]:
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame.head() #the head method selects only the first five rows:

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [37]:
pd.DataFrame(data, columns=['year','state','pop']) # a sequence of columns.

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [38]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five','six'])

In [39]:
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [43]:
frame2.loc['three']

year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [44]:
frame2['debt'] = 16.5

In [45]:
frame2

year   state  pop  debt
one    2000    ohio  1.5  16.5
two    2001    ohio  1.7  16.5
three  2002    ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [46]:
frame2['debt'] = np.arange(6.)

In [47]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   0.0
two    2001    ohio  1.7   1.0
three  2002    ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [48]:
val = pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])

In [49]:
frame2['debt'] = val

In [50]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [51]:
frame2['eastern'] = frame2.state == 'ohio'

In [52]:
frame2

year   state  pop  debt  eastern
one    2000    ohio  1.5   NaN     True
two    2001    ohio  1.7  -1.2     True
three  2002    ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [53]:
del frame2['eastern']

In [54]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [55]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [56]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [57]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [58]:
frame3 = pd.DataFrame(pop)

In [59]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [60]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [61]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [62]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [63]:
pd.DataFrame(pdata) # Their have some error but excute okay.


Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [64]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [65]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [66]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [67]:
frame2.values

array([[2000, 'ohio', 1.5, nan],
       [2001, 'ohio', 1.7, -1.2],
       [2002, 'ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [68]:
obj = pd.Series(range(3), index=['a','b','c'])

In [69]:
index = obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index[1:]

Index(['b', 'c'], dtype='object')

In [72]:
index[1] = 'd' #TypeError

TypeError: Index does not support mutable operations

In [73]:
labels = pd.Index(np.arange(3))

In [74]:
labels

Index([0, 1, 2], dtype='int64')

In [75]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)

In [76]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [77]:
obj2.index is labels

True

In [78]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [79]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [80]:
'Ohio' in frame3.columns

True

In [81]:
2003 in frame3.index

False

In [82]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [83]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

## Essential Functionality

### Reindexing

In [84]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])

In [85]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [86]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [87]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [88]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])

In [89]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [90]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [91]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns=['Ohio','Texas','California'])

In [92]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [93]:
frame2 = frame.reindex(['a','b','c','d'])

In [94]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [95]:
states = ['Texas','Utah','California']

In [96]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [97]:
frame.loc[['a', 'b', 'c', 'd'], states]

KeyError: "['b'] not in index"

### Dropping Entries from an Axis

In [ ]:
obj = pd.Series(np.arange(5.), index=['a','b','c','d','e'])

In [ ]:
obj

In [ ]:
new_obj = obj.drop('c')

In [ ]:
new_obj

In [ ]:
obj.drop(['d','c'])

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])

In [ ]:
data

In [98]:
data.drop(['Colorado','Ohio'])

AttributeError: 'dict' object has no attribute 'drop'

In [99]:
data.drop('two', axis=1)

AttributeError: 'dict' object has no attribute 'drop'

In [100]:
data.drop(['two','four'], axis='columns')

AttributeError: 'dict' object has no attribute 'drop'

In [101]:
obj.drop('c',inplace=True)

In [102]:
obj

d    4.5
b    7.2
a   -5.3
dtype: float64

### Indexing,Selection,and filtering

In [103]:
obj = pd.Series(np.arange(4.), index=['a','b','c','d'])

In [104]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [105]:
obj['b']

np.float64(1.0)

In [106]:
obj[1]

C:\Users\Hemant\AppData\Local\Temp\ipykernel_18132\2469632899.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[1]


np.float64(1.0)

In [107]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [108]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [109]:
obj[[1,3]]

C:\Users\Hemant\AppData\Local\Temp\ipykernel_18132\1781339481.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  obj[[1,3]]


b    1.0
d    3.0
dtype: float64

In [110]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [111]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [112]:
obj['b':'c']=5

In [113]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [114]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index=['Ohio','Colorado','Utah','New York'],
                   columns=['one','two','three','four'])

In [115]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [116]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [117]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [118]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [119]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [120]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [121]:
data[data<5] = 0

In [122]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

##### Selection with loc and iloc

In [123]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

In [124]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [125]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [126]:
data.iloc[[1,2],[3,0,1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [127]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [128]:
data.iloc[:, :3][data.three>5] #how?

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

### Integer Indexes

In [129]:
ser = pd.Series(np.arange(3.))

In [130]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [131]:
ser[-1] # Because it is integer indexing.

KeyError: -1

In [ ]:
ser2 = pd.Series(np.arange(3.), index=['a','b','c'])

In [ ]:
ser2[-1]

In [ ]:
ser[:1]

In [ ]:
ser.loc[:1]

In [ ]:
ser.iloc[:1]

### Arithmetic and Data Alignment

In [ ]:
s1= pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [ ]:
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1],
              index=['a','c','e','f','g'])

In [ ]:
s1

In [ ]:
s2

In [ ]:
s1+s2

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                  columns=list('bcd'),
                  index=['Ohio','Texas','Colorado'])

In [ ]:
df2 = pd.DataFrame(np.arange(12. ).reshape((4, 3)),
                  columns=list('bde'),
                  index=['Utah','Ohio','Texas','Oregon'])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1+df2

In [ ]:
df1 = pd.DataFrame({'A':[1,2]})

In [ ]:
df2 = pd.DataFrame({'B':[3,4]})

In [132]:
df1

NameError: name 'df1' is not defined

In [133]:
df2

NameError: name 'df2' is not defined

In [134]:
df1-df2

NameError: name 'df1' is not defined

#### Arithmetic methods with fill values

In [135]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                  columns=list('abcd'))

In [136]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                  columns=list('abcde'))

In [137]:
df2.loc[1, 'b'] = np.nan #nan is NAN this is numpy lib. 

In [138]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [139]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [140]:
df1+df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [141]:
df1.add(df2, fill_value=0) # using add method on df1, to pass df2 and an argument to fill_value:

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [142]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [143]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [144]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

#### Operations between DataFrame and Series

In [145]:
arr = np.arange(12. ).reshape((3, 4))

In [146]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [147]:
arr[0]

array([0., 1., 2., 3.])

In [148]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [149]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                    columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])

In [150]:
series = frame.iloc[0]

In [151]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [152]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [153]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [154]:
series2 = pd.Series(range(3), index=['b','e','f'])

In [155]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [156]:
series3 = frame['d']

In [157]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [158]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [159]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

### Function Application and Mapping

In [160]:
frame = pd.DataFrame(np.random.randn(4, 3),
                    columns=list('bde'),
                    index=['Utah','Ohio','Texas','Oregon'])

In [161]:
frame

b         d         e
Utah    1.569651 -0.149046 -0.381668
Ohio    0.351562 -0.712466  0.078986
Texas   1.496549 -0.195042 -0.591976
Oregon  1.599703  1.579772 -0.054326

In [162]:
np.abs(frame)

b         d         e
Utah    1.569651  0.149046  0.381668
Ohio    0.351562  0.712466  0.078986
Texas   1.496549  0.195042  0.591976
Oregon  1.599703  1.579772  0.054326

In [163]:
f = lambda x: x.max() - x.min()

In [164]:
frame.apply(f)

b    1.248141
d    2.292239
e    0.670962
dtype: float64

In [165]:
frame.apply(f,axis='columns')

Utah      1.951320
Ohio      1.064028
Texas     2.088524
Oregon    1.654029
dtype: float64

In [166]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min','max'])

In [167]:
frame.apply(f)

b         d         e
min  0.351562 -0.712466 -0.591976
max  1.599703  1.579772  0.078986

In [168]:
format = lambda x: '%.2f' % x

In [169]:
frame.applymap(format)

C:\Users\Hemant\AppData\Local\Temp\ipykernel_18132\304758519.py:1: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  frame.applymap(format)


b      d      e
Utah    1.57  -0.15  -0.38
Ohio    0.35  -0.71   0.08
Texas   1.50  -0.20  -0.59
Oregon  1.60   1.58  -0.05

In [170]:
frame['e'].map(format)

Utah      -0.38
Ohio       0.08
Texas     -0.59
Oregon    -0.05
Name: e, dtype: object

### Sorting and Ranking

In [171]:
obj = pd.Series(range(4), index=['d','a','b','c'])

In [172]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [173]:
frame = pd.DataFrame(np.arange(8).reshape((2,4)),
                    index=['three','one'],
                     columns=['d','a','b','c'])

In [174]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [175]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [176]:
frame.sort_index(axis=1, ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [177]:
obj=pd.Series([4,7,-3,2])

In [178]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [179]:
obj = pd.Series([4,np.nan,7,np.nan,-3,2])

In [180]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [181]:
frame= pd.DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [182]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [183]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [184]:
frame.sort_values(by=['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [185]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [186]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [187]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [188]:
# Assign tie values the maximum rank in the group
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [189]:
frame = pd.DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [190]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [191]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

### Axis indexes with Duplicate Labels

In [192]:
obj = pd.Series(range(5), index=['a','a','b','b','c'])

In [193]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [194]:
obj.index.is_unique

False

In [195]:
obj['a']

a    0
a    1
dtype: int64

In [196]:
obj['c']

np.int64(4)

In [197]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a','a','b','b'])

In [198]:
df

0         1         2
a -0.536727 -0.625121  0.353740
a -0.153638  0.983122  0.546061
b  0.191336 -0.501648 -1.768066
b -2.142020 -0.495783 -0.314268

In [199]:
df.loc['b']

0         1         2
b  0.191336 -0.501648 -1.768066
b -2.142020 -0.495783 -0.314268

## Summarizing and Computing Descriptive Statistics

In [200]:
df = pd.DataFrame([[1.4,np.nan], [7.1,-4.5],[np.nan,np.nan],[0.75,-1.3]],
                 index=['a','b','c','d'],
                 columns=['one','two'])

In [201]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [202]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [203]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [204]:
df.mean(axis='columns',skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [205]:
df.idxmax()

one    b
two    d
dtype: object

In [206]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [207]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [208]:
obj = pd.Series(['a','a','b','c']*4)

In [209]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

### Correlation and Covariance

In [210]:
import pandas_datareader.data as web

In [211]:
all_data = {ticker: web.get_data_yahoo(ticker )
           for ticker in ['AAPL','IBM','MSFT','GOOG']}
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})
volume = pd.DataFrame({ticker: data['bVolume']
                      for ticker, data in all_data.items()})

RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/AAPL/history?period1=1603405800&period2=1761172199&interval=1d&frequency=1d&filter=history
Response Text:
b'<html><meta charset=\'utf-8\'>\n<script>\nif(window != window.top){\ndocument.write(\'<p>Content is currently unavailable.</p><img src="//geo.yahoo.com/p?s=1197757039&t=\'\n    + new Date().getTime() + \'&_R=\'\n    + encodeURIComponent(document.referrer)\n    + \'&err=404\'\n    + \'" width="0px" height="0px"/>\');\n}else{\nwindow.location.replace(\'https://\' + window.location.host + \'/?err=404\');\n}\n</script>\n<noscript>\n<META http-equiv="refresh" content="0;URL=https://finance.yahoo.com/?err=404">\n</noscript></html>'

### Unique values, Value Counts, and Membership

In [212]:
obj = pd.Series(['c','a','d','a','a','b','b','c','c'])

In [213]:
uniques = obj.unique()

In [214]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [215]:
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [216]:
pd.value_counts(obj.values, sort=False)

C:\Users\Hemant\AppData\Local\Temp\ipykernel_18132\3084372382.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

In [217]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [218]:
mask = obj.isin(['b','c'])

In [219]:
mask

0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [220]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [221]:
to_match = pd.Series(['c','a','b','c','a'])

In [222]:
unique_vals = pd.Series(['c','b','a'])

In [223]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 0, 2])

In [ ]:
data = pd.DataFrame({'Qu1':[1,3,4,3,4],
                     'Qu2':[2,3,1,2,3],
                     'Qu3'