# Getting start with pandas
## Introduction to pandas Data Structures


In [1]:
import pandas as pd 
import numpy as np

In [2]:
from pandas import Series, DataFrame

### Series

In [3]:
obj = pd.Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3])

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [10]:
obj2['a']

np.int64(-5)

In [11]:
obj2['d'] = 6

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    6
dtype: int64

In [13]:
obj2[obj2 > 0]

d    6
b    7
c    3
dtype: int64

In [14]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2

True

In [17]:
'e' in obj2

False

In [18]:
 sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [19]:
obj3 = pd.Series(sdata)

In [20]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [21]:
states = ['California', 'Ohio', 'Oregon', 'Texas']

In [22]:
obj4 = pd.Series(sdata, index=states)

In [23]:
obj4


California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [25]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

### DataFrame

In [34]:
data = {'state':['ohio','ohio','ohio','Nevada','Nevada','Nevada'],
       'year':[2000,2001,2002,2001,2002,2003],
       'pop':[1.5,1.7,3.6,2.4,2.9,3.2]}
frame = pd.DataFrame(data)

In [35]:
frame

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [36]:
frame.head() #the head method selects only the first five rows:

state  year  pop
0    ohio  2000  1.5
1    ohio  2001  1.7
2    ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [37]:
pd.DataFrame(data, columns=['year','state','pop']) # a sequence of columns.

year   state  pop
0  2000    ohio  1.5
1  2001    ohio  1.7
2  2002    ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [38]:
frame2 = pd.DataFrame(data, columns=['year','state','pop','debt'],
                     index=['one','two','three','four','five','six'])

In [39]:
frame2

year   state  pop debt
one    2000    ohio  1.5  NaN
two    2001    ohio  1.7  NaN
three  2002    ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [40]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [41]:
frame2['state']

one        ohio
two        ohio
three      ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [42]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [43]:
frame2.loc['three']

year     2002
state    ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [55]:
frame2['debt'] = 16.5

In [56]:
frame2

year   state  pop  debt  dept
one    2000    ohio  1.5  16.5   0.0
two    2001    ohio  1.7  16.5   1.0
three  2002    ohio  3.6  16.5   2.0
four   2001  Nevada  2.4  16.5   3.0
five   2002  Nevada  2.9  16.5   4.0
six    2003  Nevada  3.2  16.5   5.0

In [59]:
frame2['debt'] = np.arange(6.)

In [60]:
frame2

year   state  pop  debt  dept
one    2000    ohio  1.5   0.0   0.0
two    2001    ohio  1.7   1.0   1.0
three  2002    ohio  3.6   2.0   2.0
four   2001  Nevada  2.4   3.0   3.0
five   2002  Nevada  2.9   4.0   4.0
six    2003  Nevada  3.2   5.0   5.0

In [61]:
val = pd.Series([-1.2,-1.5,-1.7], index=['two','four','five'])

In [62]:
frame2['debt'] = val

In [63]:
frame2

year   state  pop  debt  dept
one    2000    ohio  1.5   NaN   0.0
two    2001    ohio  1.7  -1.2   1.0
three  2002    ohio  3.6   NaN   2.0
four   2001  Nevada  2.4  -1.5   3.0
five   2002  Nevada  2.9  -1.7   4.0
six    2003  Nevada  3.2   NaN   5.0

In [64]:
frame2['eastern'] = frame2.state == 'ohio'

In [65]:
frame2

year   state  pop  debt  dept  eastern
one    2000    ohio  1.5   NaN   0.0     True
two    2001    ohio  1.7  -1.2   1.0     True
three  2002    ohio  3.6   NaN   2.0     True
four   2001  Nevada  2.4  -1.5   3.0    False
five   2002  Nevada  2.9  -1.7   4.0    False
six    2003  Nevada  3.2   NaN   5.0    False

In [66]:
del frame2['eastern']

In [67]:
frame2

year   state  pop  debt  dept
one    2000    ohio  1.5   NaN   0.0
two    2001    ohio  1.7  -1.2   1.0
three  2002    ohio  3.6   NaN   2.0
four   2001  Nevada  2.4  -1.5   3.0
five   2002  Nevada  2.9  -1.7   4.0
six    2003  Nevada  3.2   NaN   5.0

In [68]:
del frame2['dept']

In [69]:
frame2

year   state  pop  debt
one    2000    ohio  1.5   NaN
two    2001    ohio  1.7  -1.2
three  2002    ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [70]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [87]:
pop = {'Nevada':{2001:2.4,2002:2.9},
      'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [88]:
frame3 = pd.DataFrame(pop)

In [89]:
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [90]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [91]:
pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [94]:
pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [96]:
pd.DataFrame(pdata) # Their have some error but excute okay.


Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [99]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [100]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [101]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [102]:
frame2.values

array([[2000, 'ohio', 1.5, nan],
       [2001, 'ohio', 1.7, -1.2],
       [2002, 'ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

### Index Objects

In [104]:
obj = pd.Series(range(3), index=['a','b','c'])

In [105]:
index = obj.index

In [106]:
index

Index(['a', 'b', 'c'], dtype='object')

In [107]:
index[1:]

Index(['b', 'c'], dtype='object')

In [108]:
index[1] = 'd' #TypeError

TypeError: Index does not support mutable operations

In [109]:
labels = pd.Index(np.arange(3))

In [110]:
labels

Index([0, 1, 2], dtype='int64')

In [112]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)

In [114]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [115]:
obj2.index is labels

True

In [116]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [118]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [119]:
'Ohio' in frame3.columns

True

In [120]:
2003 in frame3.index

False

In [121]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [122]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [123]:
 #Table 5-2. Some Index methods and properties
 # Method                    Description
 # append                    Concatenate with additional Index objects, producing a new Index
 # difference                Compute set difference as an Index
 # intersection              Compute set intersection
 # union                     Compute set union
 # isin                      Compute boolean array indicating whether each value is contained in the passed collection
 # delete                    Compute new Index with element at index i deleted
 # drop                      Compute new Index by deleting passed values
 # insert                    Compute new Index by inserting element at index i
 # is_monotonic              Returns True if each element is greater than or equal to the previous element
 # is_unique                 Returns True if the Index has no duplicate values
 # unique                    Compute the array of unique values in the Index
 # 

## Essential Functionality

### Reindexing

In [124]:
obj = pd.Series([4.5,7.2,-5.3,3.6], index=['d','b','a','c'])

In [125]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [126]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [127]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [128]:
obj3 = pd.Series(['blue','purple','yellow'], index=[0,2,4])

In [129]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [131]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [132]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                    index=['a','c','d'],
                    columns=['Ohio','Texas','California'])

In [133]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [134]:
frame2 = frame.reindex(['a','b','c','d'])

In [136]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [137]:
states = ['Texas','Utah','California']

In [140]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [141]:
frame.loc[['a','b','c','d'],states]

KeyError: "['b'] not in index"