# NumPy Basics.

In [5]:
import numpy as np

In [6]:
my_arr = np.arange(1000000)

In [7]:
my_list = list (range(1000000))

In [18]:
%time for _ in range(10): my_arr2 = my_arr*2

CPU times: total: 31.2 ms
Wall time: 25.9 ms


In [20]:
%time for _ in range(10): my_list2 = [x * 2 for x in  my_list]

CPU times: total: 484 ms
Wall time: 487 ms


## The NumPy ndarry : A Multidimensional Array Object

In [21]:
# Generate some random data 
data = np.random .randn(2, 3)

In [22]:
data

array([[ 1.10721891, -0.43735946, -0.45039787],
       [ 1.2328963 ,  0.52526323, -1.72265576]])

In [23]:
data * 10

array([[ 11.07218908,  -4.37359464,  -4.5039787 ],
       [ 12.32896302,   5.25263226, -17.22655761]])

In [24]:
data + data

array([[ 2.21443782, -0.87471893, -0.90079574],
       [ 2.4657926 ,  1.05052645, -3.44531152]])

In [25]:
# shape

In [26]:
data.shape

(2, 3)

In [27]:
data.dtype

dtype('float64')

### Creating ndarrays

In [28]:
data1 = [6,7.5,8,0,1]

In [29]:
arr1 = np.array(data1)

In [30]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [31]:
data2 = [[1,2,3,4], [5,6,7,8]]

In [32]:
arr2 = np.array(data2)

In [33]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [34]:
arr2.ndim

2

In [35]:
arr2.shape

(2, 4)