 # NumPy Basics: Arrays and Vectorized Computation

In [2]:
import numpy as np

In [3]:
my_arr = np.arange(1000000)

In [4]:
my_list = list(range(1000000))

In [5]:
 %time for _ in range(10): my_arr2 = my_arr * 2

CPU times: total: 31.2 ms
Wall time: 27.2 ms


In [6]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: total: 453 ms
Wall time: 469 ms


In [8]:
data = np.random.randn(2,3)

In [9]:
data

array([[-1.35619092, -0.08718592,  0.18504922],
       [-2.76485038, -1.23515539, -1.8838491 ]])

In [10]:
data *10

array([[-13.56190921,  -0.87185917,   1.85049219],
       [-27.64850375, -12.35155386, -18.83849099]])

In [11]:
data + data

array([[-2.71238184, -0.17437183,  0.37009844],
       [-5.52970075, -2.47031077, -3.7676982 ]])

In [12]:
data.shape

(2, 3)